---
- name: Ensure Raspberry Pi is configured
  hosts: all
  become: true
  tasks:
    - name: Ensure `pi` user is disabled
      user:
        name: pi
        expires: 0

    - name: Ensure `root` cannot login via SSH
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "^PermitRootLogin"
        line: PermitRootLogin no
      notify: Restart sshd

    - name: Ensure `sshd` password authentication is disabled
      become: true
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "^PasswordAuthentication"
        line: PasswordAuthentication no
      notify: Restart sshd

    - name: Ensure system is up-to-date
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400 # one day
      notify: Reboot the system

    - name: Flush handlers to reboot the system
      meta: flush_handlers

    - name: Ensure `fail2ban` is installed
      package:
        name: fail2ban

    # - name: Ensure `containerd.io` is installed
    #   apt:
    #     deb: https://download.docker.com/linux/debian/dists/buster/pool/stable/armhf/containerd.io_1.4.9-1_armhf.deb
    #     # deb: https://download.docker.com/linux/debian/dists/buster/pool/stable/amd64/containerd.io_1.4.9-1_amd64.deb

    # - name: Ensure `docker-ce-cli` is installed
    #   apt:
    #     deb: https://download.docker.com/linux/debian/dists/buster/pool/stable/armhf/docker-ce-cli_20.10.8~3-0~debian-buster_armhf.deb
    #     # deb: https://download.docker.com/linux/debian/dists/buster/pool/stable/amd64/docker-ce-cli_20.10.8~3-0~debian-buster_amd64.deb

    # - name: Ensure `docker-ce` is installed
    #   apt:
    #     deb: https://download.docker.com/linux/debian/dists/buster/pool/stable/armhf/docker-ce_20.10.8~3-0~debian-buster_armhf.deb
    #     # deb: https://download.docker.com/linux/debian/dists/buster/pool/stable/amd64/docker-ce_20.10.8~3-0~debian-buster_amd64.deb

    # - name: Ensure `docker` service starts on boot
    #   systemd:
    #     name: docker.service
    #     enabled: yes

    # - name: Ensure `containerd` service starts on boot
    #   systemd:
    #     name: containerd.service
    #     enabled: yes

    # - name: Ensure `morgan` user has group `docker`
    #   user:
    #     name: morgan
    #     groups: docker
    #     append: yes

  handlers:
    - name: Restart sshd
      service:
        name: sshd
        state: restarted

    - name: Reboot the system
      reboot:
