---
- name: Ensure Raspberry Pi is configured
  hosts: all
  become: true
  vars:
    servarr_uid: 1042
    servarr_gid: 1042
  tasks:
    - name: Ensure `pi` user is disabled
      user:
        name: pi
        state: absent

    - name: Ensure `morgan` user has up-to-date SSH keys
      authorized_key:
        user: morgan
        key: https://raw.githubusercontent.com/nagromc/dotfiles/refs/heads/main/private_dot_ssh/authorized_keys

    - name: Ensure `servarr` group is created
      group:
        name: servarr
        gid: "{{ servarr_gid }}"

    - name: Ensure `servarr` user is created
      user:
        name: servarr
        group: servarr
        password: '!'  # locked password
        shell: /usr/sbin/nologin
        uid: "{{ servarr_uid }}"

    - name: Ensure `sshd` is secured
      copy:
        src: files/etc/ssh/sshd_config.d/sshd.conf
        dest: /etc/ssh/sshd_config.d/sshd.conf
        owner: root
        group: root
        mode: 0600
      notify: Restart sshd

    - name: Ensure packages are installed
      package:
        name: docker.io
      notify: Reboot system

    - name: Ensure `morgan` user has group `docker`
      user:
        name: morgan
        groups: docker
        append: yes

    - name: Ensure system is up-to-date
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400 # one day
      notify: Reboot system

    - name: Mount volume from NAS
      mount:
        src: //mgn-nas.local/video
        path: /mnt/nas
        opts: "rw,vers=3,file_mode=0660,dir_mode=0770,uid={{ servarr_uid }},gid={{ servarr_gid }},username={{ smb_user }},password={{ smb_password }}"
        fstype: cifs
        state: mounted

  handlers:
    - name: Restart sshd
      service:
        name: sshd
        state: restarted

    - name: Reboot system
      reboot:
