---
- name: Ensure Raspberry Pi is configured
  hosts: all
  become: true
  tasks:
    - name: Ensure `pi` user is disabled
      user:
        name: pi
        expires: 0

    - name: Ensure `root` cannot login via SSH
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "^PermitRootLogin"
        line: PermitRootLogin no
      notify: Restart sshd

    - name: Ensure `sshd` password authentication is disabled
      become: true
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "^PasswordAuthentication"
        line: PasswordAuthentication no
      notify: Restart sshd

    - name: Ensure packages are installed
      package:
        name: docker.io, fail2ban
      notify: Reboot system

    - name: Ensure `morgan` user has group `docker`
      user:
        name: morgan
        groups: docker
        append: yes

    - name: Ensure system is up-to-date
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400 # one day
      notify: Reboot system

  handlers:
    - name: Restart sshd
      service:
        name: sshd
        state: restarted

    - name: Reboot system
      reboot:
